name: facebook-post-action
author: ReenigneArcher
description: GitHub Action for posting to a facebook page or group

inputs:
  page_id:
    description: "The page/group id to post to, if not set env.FACEBOOK_PAGE_ID will be used."
    required: false
  access_token:
    description: "Facebook access token, if not set env.FACEBOOK_PAGE_ID will be used."
    required: false
  message:
    description: "The message content of the post."
    required: true
  url:
    description: "The url to include with the post."
    required: false
  fail_on_error:
    description: "Set to False to allow the workflow to success for groups that don't have the app installed."
    required: false

runs:
  using: "composite"
  steps:
    - run: python -m pip install -r ${{ github.action_path }}/requirements.txt  # Installing dependencies
      shell: bash
    - run: python ${{ github.action_path }}/facebook_post_action.py
      shell: bash
      env:
        INPUT_PAGE_ID: ${{inputs.page_id}}
        INPUT_ACCESS_TOKEN: ${{inputs.access_token}}
        INPUT_MESSAGE: ${{inputs.message}}
        INPUT_URL: ${{inputs.url}}
        INPUT_FAIL_ON_ERROR: ${{inputs.fail_on_error}}

branding:
  icon: at-sign
  color: blue
